#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-ConfigMgr
version:      0.1
version_from: lib/Class/ConfigMgr.pm
installdirs:  site
requires:
    Class::ErrorHandler:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
